WIP: Numeric Exceptions
icgc-argo/argo-clinical pull request #1107
Opened 2024-01-15 19:44 UTC by demariadaniel

**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Refactor
- [ ] New Feature
- [ ] Release Candidate

**Checklist before requesting review:**

- [ ] Check branch (code change PRs go to `develop` not master)
- [ ] Check copyrights for new files
- [ ] Manual testing
- [ ] Regression tests completed and passing (double check number of tests).
- [ ] Spelling has been checked.
- [ ] Updated swagger docs accordingly (check it's still valid)
- [ ] Set `validationDependency` in meta tag for [Argo Dictionary](https://github.com/icgc-argo/argo-dictionary) fields used in code

2024-01-17 16:42 UTC, joneubank requested changes
As discussed, needs a bit of rework:
1. don't need to modify the exception request or data structure
2. need to look at the dictionary schema for each field with an exception to know if it is a string field or a number field. these two fields should have separate exception logic. strings must match the `requested_exception_value`, numbers must be `undefined`.

2024-01-17 16:42 UTC, joneubank commented on src/exception/validation.ts
> +  if (requestedExceptionValue !== undefined && !validRequests.includes(requestedExceptionValue)) {
Even before your changes, I am confused why this logic is needed... originally this property couldn't be undefined... If we restore the exception to require a string for `requested_exception_value` then we wouldn't need this `undefined` check.

2024-01-17 16:42 UTC, joneubank commented on src/submission/exceptions/exceptions.ts
> +  typeof value === 'string' || isSingleString(value) || typeof value === 'undefined';
As discussed offline, the allowed types for numeric and string fields are different. String fields are only allowed to be `string` or `[string]`. With numeric fields, we accept a number that passes validation or `undefined` with the exception, so we'd be looking for:

```ts
const isAllowedTypeForNumberFieldException = (
  value: DeepReadonly<dictionaryEntities.SchemaTypes>,
): undefined => value === undefined;
```

or similar, if needed.

2024-01-17 22:48 UTC, demariadaniel commented
Successful blank value Exception Upload for field treatment_start_interval 
<img width="1138" alt="Screenshot 2024-01-17 at 5 46 23 PM" src="https://github.com/icgc-argo/argo-clinical/assets/15621876/bbfe4671-ec92-4db6-a4a0-c25b7a60b6b4">

Test file here: (tsv not supported on Github)
[exception_test1.txt](https://github.com/icgc-argo/argo-clinical/files/13969512/exception_test1.txt)

2024-01-23 14:01 UTC, joneubank approved these changes
Looks good thanks.

2024-01-23 14:45 UTC, demariadaniel commented on src/exception/validation.ts
> +  const schemaDefinition = (await currentDictionary.getCurrent()).schemas.find(schemaFilter);
I was planning to make it reusable since we do a version of this filter a few times in the file

2024-01-23 14:46 UTC, demariadaniel commented on src/exception/validation.ts
> +  const schemaDefinition = (await currentDictionary.getCurrent()).schemas.find(schemaFilter);
I left a comment but in the wrong PR (next PR for validation)

2024-01-23 15:13 UTC, demariadaniel commented on src/exception/validation.ts
> +  const schemaDefinition = (await currentDictionary.getCurrent()).schemas.find(schemaFilter);
Updated: https://github.com/icgc-argo/argo-clinical/pull/1107/commits/5eab8e581d27627d33fe1180b0e8e8a47e38854c

2024-01-23 20:44 UTC, joneubank approved these changes

2024-01-23 21:15 UTC, merged