Merge Back 1.43.1
icgc-argo/argo-clinical pull request #629
Opened 2021-02-11 22:00 UTC by Buwujiu

**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Refactor
- [ ] New Feature
- [ ] Release Candidate

**Checklist before requesting review:**

- [ ] Check branch (code change PRs go to `develop` not master)
- [ ] Check copyrights for new files
- [ ] Manual testing
- [ ] Regression tests completed and passing (double check number of tests).
- [ ] Spelling has been checked.
- [ ] Updated swagger docs accordingly (check it's still valid)
- [ ] Set `validationDependency` in meta tag for [Argo Dictionary](https://github.com/icgc-argo/argo-dictionary) fields used in code

2021-02-11 23:56 UTC, blabadi approved these changes

2021-02-12 00:05 UTC, blabadi requested changes
something is up with the branches, there is a warning showing

2021-02-12 21:30 UTC, joneubank commented
@blabadi the warning just looks like normal saying this mergeback is needed. everything looks in order here to me, are you seeing something more?

2021-02-16 17:34 UTC, blabadi approved these changes

2021-02-22 15:22 UTC, merged