add program exception model
icgc-argo/argo-clinical pull request #821
Opened 2022-10-06 18:45 UTC by ciaranschutte

**Description of changes**

adds mongoose schema for program exceptions and methods to interact with db

**Type of Change**

- [ ] Bug
- [ ] Refactor
- [ ] New Feature
- [ ] Release Candidate

**Checklist before requesting review:**

- [ ] Check branch (code change PRs go to `develop` not master)
- [ ] Check copyrights for new files
- [ ] Manual testing
- [ ] Regression tests completed and passing (double check number of tests).
- [ ] Spelling has been checked.
- [ ] Updated swagger docs accordingly (check it's still valid)
- [ ] Set `validationDependency` in meta tag for [Argo Dictionary](https://github.com/icgc-argo/argo-dictionary) fields used in code

2022-10-07 15:10 UTC, joneubank commented
Can we rename the file to `exceptions-repo`? just to prevent us having a million files all named `repo` (plus this follows the pattern established in the submission code).

2022-10-07 15:21 UTC, joneubank requested changes
Looks good overall, just some nit picks that we can use to clean up a bit.

2022-10-07 15:21 UTC, joneubank commented on src/exception/repo.ts
> +    const programException = new ProgramExceptionModel(exception);
Why not just pass your argument directly to the model?
```suggestion
    const programException = new ProgramExceptionModel(req);
```

2022-10-07 15:21 UTC, joneubank commented on src/exception/repo.ts
> +  async update(programException: ProgramException) {
Let's just name this replace ;)

2022-10-07 16:17 UTC, ciaranschutte commented
thanks for review @joneubank - addressed feedback

2022-10-11 13:02 UTC, joneubank approved these changes
LGTM 👍

2022-10-11 17:29 UTC, merged