rc/1.75.0
icgc-argo/argo-clinical pull request #900
Opened 2023-02-09 20:10 UTC by ciaranschutte

**Description of changes**

#896 Scope Mongo Container Version
#895 Enable Debug Logs for Integration Tests
#891 Use SWC + Upgrade TS-Node
#893 Update Swagger
#897 Remove SWC
#849 Validation Rules for Program Exceptions
#884 Persistent Post Submission Errors
#890 Improved error handling for exceptions

**Type of Change**

- [ ] Bug
- [ ] Refactor
- [ ] New Feature
- [x] Release Candidate

**Checklist before requesting review:**

- [ ] Check branch (code change PRs go to `develop` not master)
- [ ] Check copyrights for new files
- [ ] Manual testing
- [ ] Regression tests completed and passing (double check number of tests).
- [ ] Spelling has been checked.
- [ ] Updated swagger docs accordingly (check it's still valid)
- [ ] Set `validationDependency` in meta tag for [Argo Dictionary](https://github.com/icgc-argo/argo-dictionary) fields used in code

2023-02-10 17:08 UTC, joneubank requested changes
@demariadaniel theres a couple places where the type casting I think is concerning. On review, I don't think this will break when run but I would like to clean this up before we merge to main. My apologies if I previously overlooked this during a review only to raise the issue now - I guess that's the value in having multiple steps to check during deployment.

2023-02-10 18:32 UTC, demariadaniel commented on src/clinical/service-worker-thread/tasks.ts
> +    const { donorId: nextDonor } = nextRecord as Donor;
@joneubank @ciaranschutte I've updated Types related to Submitted Data in https://github.com/icgc-argo/argo-clinical/pull/901

2023-02-10 18:37 UTC, demariadaniel commented on src/clinical/service-worker-thread/tasks.ts
> +    const nextEntry = nextRecord as ClinicalInfo;
Updated in #901

2023-02-10 18:37 UTC, demariadaniel commented on src/clinical/clinical-service.ts
> +          >[];
Updated in #901

2023-02-22 18:50 UTC, joneubank approved these changes

2023-02-22 18:50 UTC, merged